# Generated by Django 3.1.3 on 2020-12-04 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accounts',
        ),
    ]
