# Generated by Django 3.1.3 on 2020-12-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoyerFloors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('num_rooms', models.IntegerField()),
                ('Eligibility1', models.TextField()),
                ('Eligibility2', models.TextField()),
                ('Eligibility3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BoyerRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('Availability', models.BooleanField(default=True)),
                ('num_rooms', models.IntegerField()),
                ('Eligibility1', models.TextField()),
                ('Eligibility2', models.TextField()),
                ('Eligibility3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FalcrestAFloors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('num_rooms', models.IntegerField()),
                ('Eligibility1', models.TextField()),
                ('Eligibility2', models.TextField()),
                ('Eligibility3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FalcrestARooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('Availability', models.BooleanField(default=True)),
                ('num_rooms', models.IntegerField()),
                ('Eligibility1', models.TextField()),
                ('Eligibility2', models.TextField()),
                ('Eligibility3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FalcrestBFloors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('num_rooms', models.IntegerField()),
                ('Eligibility1', models.TextField()),
                ('Eligibility2', models.TextField()),
                ('Eligibility3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FalcrestBRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('Availability', models.BooleanField(default=True)),
                ('num_rooms', models.IntegerField()),
                ('Eligibility1', models.TextField()),
                ('Eligibility2', models.TextField()),
                ('Eligibility3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FalcrestCFloors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('num_rooms', models.IntegerField()),
                ('Eligibility1', models.TextField()),
                ('Eligibility2', models.TextField()),
                ('Eligibility3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FalcrestCRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('Availability', models.BooleanField(default=True)),
                ('num_rooms', models.IntegerField()),
                ('Eligibility1', models.TextField()),
                ('Eligibility2', models.TextField()),
                ('Eligibility3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FalcrestDFloors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('num_rooms', models.IntegerField()),
                ('Eligibility1', models.TextField()),
                ('Eligibility2', models.TextField()),
                ('Eligibility3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FalcrestDRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('Availability', models.BooleanField(default=True)),
                ('num_rooms', models.IntegerField()),
                ('Eligibility1', models.TextField()),
                ('Eligibility2', models.TextField()),
                ('Eligibility3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LathamFloors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('num_rooms', models.IntegerField()),
                ('Eligibility1', models.TextField()),
                ('Eligibility2', models.TextField()),
                ('Eligibility3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LathamRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('Availability', models.BooleanField(default=True)),
                ('num_rooms', models.IntegerField()),
                ('Eligibility1', models.TextField()),
                ('Eligibility2', models.TextField()),
                ('Eligibility3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('num_rooms', models.IntegerField()),
                ('Eligibility1', models.TextField()),
                ('Eligibility2', models.TextField()),
                ('Eligibility3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WestonFloors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('num_rooms', models.IntegerField()),
                ('Eligibility1', models.TextField()),
                ('Eligibility2', models.TextField()),
                ('Eligibility3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WestonRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('Availability', models.BooleanField(default=True)),
                ('num_rooms', models.IntegerField()),
                ('Eligibility1', models.TextField()),
                ('Eligibility2', models.TextField()),
                ('Eligibility3', models.TextField()),
            ],
        ),
    ]
