# Generated by Django 3.1.3 on 2020-12-04 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('housing', '0004_auto_20201203_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floors',
            name='Eligibility1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='floors',
            name='Eligibility2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='floors',
            name='Eligibility3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='residence',
            name='Eligibility1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='residence',
            name='Eligibility2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='residence',
            name='Eligibility3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='Eligibility1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='Eligibility2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='Eligibility3',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.TextField()),
                ('sex', models.TextField()),
                ('sport', models.TextField()),
                ('honors', models.TextField()),
                ('age', models.IntegerField()),
                ('student_id', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
