# Generated by Django 3.1.3 on 2020-12-05 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0007_auto_20201204_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='user',
            new_name='username',
        ),
    ]
