# Generated by Django 3.1.3 on 2020-12-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0009_auto_20201205_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residence',
            old_name='ath',
            new_name='athlete',
        ),
        migrations.AddField(
            model_name='residence',
            name='honors',
            field=models.BooleanField(default=False),
        ),
    ]
