# Generated by Django 3.1.3 on 2020-12-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0011_auto_20201217_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='sport',
            field=models.TextField(blank=True),
        ),
    ]
