# Generated by Django 3.1.3 on 2020-12-04 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('num_rooms', models.IntegerField()),
                ('Eligibility1', models.TextField()),
                ('Eligibility2', models.TextField()),
                ('Eligibility3', models.TextField()),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.residence')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('Availability', models.BooleanField(default=True)),
                ('num_rooms', models.IntegerField()),
                ('Eligibility1', models.TextField()),
                ('Eligibility2', models.TextField()),
                ('Eligibility3', models.TextField()),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.residence')),
            ],
        ),
        migrations.DeleteModel(
            name='BoyerFloors',
        ),
        migrations.DeleteModel(
            name='BoyerRooms',
        ),
        migrations.DeleteModel(
            name='FalcrestAFloors',
        ),
        migrations.DeleteModel(
            name='FalcrestARooms',
        ),
        migrations.DeleteModel(
            name='FalcrestBFloors',
        ),
        migrations.DeleteModel(
            name='FalcrestBRooms',
        ),
        migrations.DeleteModel(
            name='FalcrestCFloors',
        ),
        migrations.DeleteModel(
            name='FalcrestCRooms',
        ),
        migrations.DeleteModel(
            name='FalcrestDFloors',
        ),
        migrations.DeleteModel(
            name='FalcrestDRooms',
        ),
        migrations.DeleteModel(
            name='LathamFloors',
        ),
        migrations.DeleteModel(
            name='LathamRooms',
        ),
        migrations.DeleteModel(
            name='WestonFloors',
        ),
        migrations.DeleteModel(
            name='WestonRooms',
        ),
    ]
