# Generated by Django 3.1.3 on 2020-12-04 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0003_auto_20201203_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='housing.floors'),
        ),
    ]
