# Generated by Django 3.1.3 on 2020-12-04 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_auto_20201203_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='student_id',
            new_name='gpa',
        ),
    ]
