# Generated by Django 3.1.3 on 2020-12-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0006_auto_20201204_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gpa',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
