# Generated by Django 3.1.3 on 2020-12-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0008_auto_20201204_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floors',
            old_name='Eligibility1',
            new_name='sex',
        ),
        migrations.RenameField(
            model_name='residence',
            old_name='Eligibility1',
            new_name='ath',
        ),
        migrations.RenameField(
            model_name='residence',
            old_name='Eligibility2',
            new_name='classification',
        ),
        migrations.RenameField(
            model_name='residence',
            old_name='Eligibility3',
            new_name='sex',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='Eligibility1',
            new_name='sport',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='room_num',
            new_name='suit_num',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='Eligibility2',
        ),
        migrations.AddField(
            model_name='residence',
            name='sport',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_letter',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='staff',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
